# Makefile for a Project Aon Book

# Series (lw = LoneWolf, gs = GreyStar...)
SERIES=ls
# Book name
BASENAME=$(shell basename $(CURDIR))
# Language of the file
BLANG := es

# *English* book name (needed to find the image files)
ORIGSERIES=lw
ORIGBASENAME=07cd

# The rest is common for all books
include ../Makefile.common
