# Makefile for The Storms of Chai

SERIES=lw
SUBSERIES=neworder
# Book name
BASENAME=$(shell basename $(CURDIR))
# Language of the file
BLANG := en

# The rest is common for all books
include ../Makefile.common
