# Makefile for a Project Aon Book

# Series (lw = LoneWolf, gs = GreyStar, fw = Freeway Warrior...)
SERIES=lw
# Sub-series (kai, magnakai, grandmaster, neworder, shianti (Grey Star))
#SUBSERIES=kai
#SUBSERIES=magnakai
#SUBSERIES=grandmaster
#SUBSERIES=neworder
#SUBSERIES=shianti
# Book name
BASENAME=$(shell basename $(CURDIR))
# Language of the file
BLANG := en

# The rest is common for all books
include ../Makefile.common
