# Makefile for a Project Aon Book

# Series (lw = LoneWolf, gs = GreyStar...)
SERIES=fw
# Sub-series (kai, magnakai, grandmaster, neworder, shianti (Grey Star))
SUBSERIES=''
# Book name
BASENAME=$(shell basename $(CURDIR))
# Language of the file
BLANG := en

# The rest is common for all books
include ../Makefile.common
