
    <section class="backmatter" id="action">
    <meta>
     <title>Carta de Acción</title>
    </meta>

    <data>
     <illustration class="inline">
      <meta>
       <creator>JC Alvarez / Jonathan Blake</creator>
      </meta>
      <instance src="acstats.png" width="386" height="286" class="html"/>
      <instance src="acstats.gif" width="386" height="286" class="html-compatible" mime-type="image/gif" />
     </illustration>

     <illustration class="inline">
      <meta>
       <creator>JC Alvarez / Jonathan Blake</creator>
      </meta>
      <instance src="acdscplz.png" width="386" height="82" class="html"/>
      <instance src="acdscplz.gif" width="386" height="82" class="html-compatible" mime-type="image/gif" />
     </illustration>

     <illustration class="inline">
      <meta>
       <creator>JC Alvarez / Jonathan Blake</creator>
      </meta>
     <instance src="acchklst.png" width="386" height="128" class="html" mime-type="image/png" />
     <instance src="acchklst.gif" width="386" height="128" class="html-compatible" mime-type="image/gif" />
     </illustration>

     <illustration class="inline">
      <meta>
       <creator>JC Alvarez / Jonathan Blake</creator>
      </meta>
      <instance src="acitems.png" width="386" height="192" class="html"/>
      <instance src="acitems.gif" width="386" height="192" class="html-compatible" mime-type="image/gif" />
     </illustration>

     <illustration class="inline">
      <meta>
       <creator>JC Alvarez / Jonathan Blake</creator>
      </meta>
      <instance src="acbckpck.png" width="386" height="113" class="html"/>
      <instance src="acbckpck.gif" width="386" height="113" class="html-compatible" mime-type="image/gif" />
     </illustration>

     <illustration class="inline">
      <meta>
       <creator>JC Alvarez / Jonathan Blake</creator>
      </meta>
      <instance src="acspcl.png" width="386" height="280" class="html"/>
      <instance src="acspcl.gif" width="386" height="280" class="html-compatible" mime-type="image/gif" />
     </illustration>

     <illustration class="inline">
      <meta>
      <creator>Gary Chalk</creator>
      </meta>
      <instance class="pdf" src="ac1.pdf" posx="-18" posy="-180" />
     </illustration>

     <illustration class="inline">
      <meta>
      <creator>Gary Chalk</creator>
      </meta>
      <instance class="pdf" src="ac2.pdf" posx="-20" posy="-180" />
     </illustration>

     <illustration class="inline">
      <meta>
      <creator>Gary Chalk</creator>
      </meta>
      <instance class="pdf" src="ac3.pdf" posx="-19" posy="-180" />
     </illustration>

<!--
    <illustration class="inline">
     <meta>
      <creator>Jonathan Blake</creator>
     </meta>
     <instance src="ac1.tex" width="400" height="500" class="tex" />
    </illustration>

    <illustration class="inline">
     <meta>
      <creator>Jonathan Blake</creator>
     </meta>
     <instance src="ac2.tex" width="400" height="500" class="tex" />
    </illustration>
--> 

    <illustration>
     <meta>
      <creator>Jonathan Blake</creator>
     </meta>
     <instance class="text">
      <p>
       <line><typ class="attribute">DESTREZA EN EL COMBATE</typ>: <ch.blankline/></line>
       <line><typ class="attribute">RESISTENCIA</typ>: <ch.blankline/></line>
      </p>
      <p>Disciplinas del Magnakai:</p>
       <ol>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
       </ol>
      <p>Armas:</p>
       <ol>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
       </ol>
      <p>Bolsa: <ch.blankline/></p>
      <p>Comidas: <ch.blankline/></p>
      <p>Objetos de mochila:</p>
       <ol>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
       </ol>
      <p>Objetos especiales:</p>
       <ol>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
        <li><ch.blankline/></li>
       </ol>
     </instance>
    </illustration>
    </data>
   </section>

