# Makefile for a Project Aon Book

# Series (lw = LoneWolf, gs = GreyStar, fw = Freeway Warrior...)
SERIES=ls
# Book name
BASENAME=$(shell basename $(CURDIR))
# Language of the file
BLANG := en

# *English* book name (needed to find the image files)
ORIGSERIES=lw
ORIGBASENAME=13tplor


# The rest is common for all books
include ../Makefile.common
